import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { inter, heebo } from './fonts';
import { getServerTranslations } from './i18n/server';
import { I18nProvider } from './i18n/client';
import './globals.css';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const translations = await getServerTranslations();
  
  return (
    <html lang="he" dir="rtl" className={`${inter.variable} ${heebo.variable}`}>
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        <I18nProvider translations={translations}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
